### ISSUE TITLE
Date! has zone setting bug, is not well behaved.

### ISSUE THREAD

**Issue by codebybrett** [metaeducation/ren-c#608]
Setting zone to 0:00 on a date with existing time and zone adjusts to UTC, but subsequent setting of zone performs no adjustment. This is inconsistent and represents a bug:

    >> d: 1-aug-2017/17:00+10:00
    == 1-Aug-2017/17:00+10:00
    >> d/zone: 0:00
    == 0:00
    >> d
    == 1-Aug-2017/7:00
    >> d/zone: 10:00
    == 10:00
    >> d
    == 1-Aug-2017/7:00+10:00

Setting zone on a date that has no time component creates time components, but ignores the given zone.

    >> d: now/date
    == 4-Aug-2017
    >> d/zone: 10:00
    == 10:00
    >> d
    == 4-Aug-2017/0:00
    >> d/zone
    == 0:00

A date can exist without a time and zone component, but it seems one cannot unset the time or zone components once they exist.

To represent a local relative time it would be useful to be able to have a date with a time component but an unset zone component.

**Comment by hostilefork** [comment]
I see what the problem is.  There's a relatively sane workaround for it.

What should `now/utc` return?  Or should it exist at all, and just have you set `now/zone: 0:00` or `now/zone: ()` 

*(`unset 'now/zone` won't work as written for some technical reasons)*

We can have `now/utc` and even `now/local` since /local has been reclaimed as a refinement.

**Comment by codebybrett** [comment]
I probably should have noted that R3 Alpha does not appear to do the automatic adjustment when setting zone to 0:00.

For a date-time-zone, `/utc` should subtract zone from date-time resulting in a new date-time-zone where zone is 0:00.  `now/zone: 0:00` is not equivalent

`d: 5-aug-2017`
D specifies a date only

`d/time: 10:30`
D now specifies a date with local time - is not bound to any particular timezone.
iCalendar describes this as [DATE WITH LOCAL TIME](https://tools.ietf.org/html/rfc5545#section-3.3.5)

`d/zone: 10:00`
D now specifies a date and time for a specific timezone.

When zone is 0:00 it should not be automatically hidden since presence or absence of zone indicates different meanings.

**Comment by hostilefork** [comment]
So if you can write the tests for what you want the behavior to be, and add them, that's very helpful.  It might help to go over Red's date tests and put in any that you agree with:

https://github.com/red/red/blob/master/tests/source/units/date-test.red

*(We should either be able to run their test format, or have a converter that can make the Rebol test format...but be able to update and respect any tests that were removed.  Perhaps that could be done by annotating a git fork of the Red tests with "doesn't apply", keep it merged and periodically regenerate.  Either way...good to leverage the work.)*

One area I just mentioned in chat involves equality and inequality, and other comparison rules, for dates that are missing parts vs. dates that have them:

https://chat.stackoverflow.com/transcript/message/38512843#38512843

**Comment by hostilefork** [comment]
The specific issue in this ticket is hopefully addressed here:

https://github.com/metaeducation/ren-c/pull/609

Beyond that, it looks like we've got some agreements on the direction for dates.  I don't know exactly when it will be worth it to go through and do the agreed-upon work; it's detail-oriented C code that I'd rather not spend time on if I can avoid it.  But let me know if any bugs are interfering with what you're trying to do.

**Comment by codebybrett** [comment]
Great! Thank you.

I've added "look at date tests" to my to do list.

**Comment by codebybrett** [comment]
I don't want to annoy with date, and #609 allows us to clear time and zone which is great, but I think zone setting is still a problem.

As soon as zone is modified, the time is adjusted to the equivalent UTC time.

    >> d: 7-aug-2017/03:00+10:00
    == 7-Aug-2017/3:00+10:00
    >> d/utc
    == 6-Aug-2017/17:00+0:00
    >> d/zone: 3:00
    == 3:00
    >> d
    == 6-Aug-2017/17:00+3:00 ; Ended up with UTC time and specified zone.

I'll propose some date tests and we can see what people think.

**Comment by codebybrett** [comment]
Proposed tests: https://forum.rebol.info/t/how-to-deal-with-users-mutating-date-and-time-to-be-invalid/240/6?u=brett
